### PR TITLE
Revert go_kraken/websocket package

### LINKED ISSUE #13: Handle panic if socket closes
Looking to a `feederd` in a staging machine, the service restarted after a panic  due a websokcet closing

Stack trace:

```
time="2021-03-05T08:45:26Z" level=info msg="Market 6f02-ce09 | Base Price 2.148371e-05 | Quote Price 46546.9"
2021/03/05 08:46:36 Heartbeat
2021/03/05 08:46:36 waiting 1s until reconnect...
2021/03/05 08:46:37 reconnect attempt 1/5
2021/03/05 08:46:37 connecting ws to wss://ws.kraken.com
2021/03/05 08:46:37 socket disconnect
2021/03/05 08:46:37 waiting 1s until reconnect...
2021/03/05 08:46:38 websocket connection closed
2021/03/05 08:46:38 reconnect failed: websocket connection closed
2021/03/05 08:46:38 socket disconnect: websocket connection closed
2021/03/05 08:46:38 Shutdown listen upstream
2021/03/05 08:46:38 Shutdown listen upstream
2021/03/05 08:46:38 Shutdown control heartbeat
2021/03/05 08:46:38 reconnect attempt 1/5
2021/03/05 08:46:38 websocket connection closed
2021/03/05 08:46:38 reconnect failed: websocket connection closed
panic: send on closed channel

goroutine 37 [running]:
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).close(...)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:283
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).exit(...)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:258
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reconnect(0xc000120820, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:245 +0x389
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).listenDisconnect(0xc000120820)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:149 +0x345
created by github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reset
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:189 +0x58
time="2021-03-05T08:46:39Z" level=info msg="Connected to gRPC: tdexd:9000"
2021/03/05 08:46:39 ----Kraken Client Parameters----
2021/03/05 08:46:39 AutoReconnect=true
2021/03/05 08:46:39 ReconnectInterval=1s
2021/03/05 08:46:39 ReconnectAttempts=5
2021/03/05 08:46:39 ShutdownTimeout=5s
2021/03/05 08:46:39 ResubscribeOnReconnect=true
2021/03/05 08:46:39 HeartbeatTimeout=3s
2021/03/05 08:46:39 URL=wss://ws.kraken.com
2021/03/05 08:46:39 connecting ws to wss://ws.kraken.com
time="2021-03-05T08:46:39Z" level=info msg="Start the feeder..."
2021/03/05 08:46:39 Status: online
2021/03/05 08:46:39 Connection ID: 16140015957635160823
2021/03/05 08:46:39 Version: 1.8.1
time="2021-03-05T08:46:39Z" level=info msg="Kraken web socket feed is listening"
2021/03/05 08:46:39 Pong received
2021/03/05 08:46:39 	Status: subscribed
2021/03/05 08:46:39 	Pair: XBT/USDT
2021/03/05 08:46:39 	Subscription: ticker
2021/03/05 08:46:39 	Channel ID: 2308
2021/03/05 08:46:39 	Req ID: 
time="2021-03-05T08:46:40Z" level=info msg="Market 6f02-ce09 | Base Price 2.1413276e-05 | Quote Price 46700"

```

### LINKED ISSUE #19: Heartbeat if socket won't reconnect.
Sometimes especially after a crash, the websocket attempt to recconect failing to do this. This will push wrong prices into the feeder somehow.

```
time="2021-04-27T08:12:03Z" level=info msg="Market 6f02-ce09 | Base Price 1.8265073e-05 | Quote Price 54749.3"
time="2021-04-27T08:12:21Z" level=info msg="Market 6f02-ce09 | Base Price 1.8271181e-05 | Quote Price 54731"
time="2021-04-27T08:12:37Z" level=info msg="Market 6f02-ce09 | Base Price 1.8274986e-05 | Quote Price 54719.6"
time="2021-04-27T08:13:50Z" level=info msg="Market 6f02-ce09 | Base Price 1.8263805e-05 | Quote Price 54753.1"
2021/04/27 08:14:24 Heartbeat
2021/04/27 08:14:24 waiting 1s until reconnect...
2021/04/27 08:14:25 reconnect attempt 1/5
2021/04/27 08:14:25 connecting ws to wss://ws.kraken.com
2021/04/27 08:14:25 socket disconnect
2021/04/27 08:14:25 waiting 1s until reconnect...
2021/04/27 08:14:26 websocket connection closed
2021/04/27 08:14:26 reconnect failed: websocket connection closed
2021/04/27 08:14:26 socket disconnect: websocket connection closed
2021/04/27 08:14:26 Shutdown listen upstream
2021/04/27 08:14:26 Shutdown listen upstream
2021/04/27 08:14:26 Shutdown control heartbeat
2021/04/27 08:14:26 reconnect attempt 1/5
2021/04/27 08:14:26 Shutdown listen disconnect
2021/04/27 08:14:26 Shutdown listen upstream
2021/04/27 08:14:26 Shutdown control heartbeat
2021/04/27 08:14:26 websocket connection closed
2021/04/27 08:14:26 reconnect failed: websocket connection closed
panic: send on closed channel

goroutine 70 [running]:
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).close(...)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:283
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).exit(...)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:258
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reconnect(0xc0002140a0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:245 +0x389
github.com/aopoltorzhicky/go_kraken/websocket.(*Client).listenDisconnect(0xc0002140a0)
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:149 +0x345
created by github.com/aopoltorzhicky/go_kraken/websocket.(*Client).reset
	/go/pkg/mod/github.com/aopoltorzhicky/go_kraken/websocket@v0.0.10/client.go:189 +0x58
time="2021-04-27T08:14:27Z" level=info msg="Connected to gRPC: tdexd:9000"
2021/04/27 08:14:27 ----Kraken Client Parameters----
2021/04/27 08:14:27 AutoReconnect=true
2021/04/27 08:14:27 ReconnectInterval=1s
2021/04/27 08:14:27 ReconnectAttempts=5
2021/04/27 08:14:27 ShutdownTimeout=5s
2021/04/27 08:14:27 ResubscribeOnReconnect=true
2021/04/27 08:14:27 HeartbeatTimeout=3s
2021/04/27 08:14:27 URL=wss://ws.kraken.com
2021/04/27 08:14:27 connecting ws to wss://ws.kraken.com
2021/04/27 08:14:30 Heartbeat
2021/04/27 08:14:46 Status: online
2021/04/27 08:14:46 Connection ID: 8632054648539031519
2021/04/27 08:14:46 Version: 1.8.3
time="2021-04-27T08:14:46Z" level=info msg="Start the feeder..."
2021/04/27 08:14:46 waiting 1s until reconnect...
time="2021-04-27T08:14:46Z" level=info msg="Kraken web socket feed is listening"
2021/04/27 08:14:47 reconnect attempt 1/5
2021/04/27 08:14:47 connecting ws to wss://ws.kraken.com
2021/04/27 08:14:47 socket disconnect
2021/04/27 08:14:47 waiting 1s until reconnect...
2021/04/27 08:14:48 reconnect attempt 1/5
2021/04/27 08:14:48 socket disconnect
2021/04/27 08:14:48 waiting 1s until reconnect...
2021/04/27 08:14:49 reconnect attempt 1/5
2021/04/27 08:14:49 socket disconnect
2021/04/27 08:14:49 waiting 1s until reconnect...
2021/04/27 08:14:50 reconnect OK
2021/04/27 08:14:50 connecting ws to wss://ws.kraken.com
2021/04/27 08:14:51 reconnect attempt 1/5
2021/04/27 08:14:51 reconnect OK
2021/04/27 08:14:51 socket disconnect
2021/04/27 08:14:51 waiting 1s until reconnect...
2021/04/27 08:14:51 reconnect OK
2021/04/27 08:14:51 connecting ws to wss://ws.kraken.com
2021/04/27 08:14:51 reconnect OK
2021/04/27 08:14:52 reconnect attempt 1/5
2021/04/27 08:14:52 reconnect OK
2021/04/27 08:14:52 socket disconnect
2021/04/27 08:14:52 waiting 1s until reconnect...
2021/04/27 08:14:53 reconnect attempt 1/5
2021/04/27 08:14:53 reconnect OK
2021/04/27 08:14:53 socket disconnect

```

### LINKED ISSUE #20: Remove address from KrakenWebSocket interface and its implementations
https://github.com/TDex-network/tdex-feeder/blob/3ae029cc28c85bc0ad547847c561b79d209cb31a/internal/ports/kraken_websocket.go#L31-L32

`address` is not used in `Connect` ---> kraken WS endpoint is not configurable via `go_kraken`. we should remove (also from config file)

### PR DESCRIPTION
**Pull request by louisinger**
**This PR removes `go_kraken`, and reuses v0.0.1 WebSocket implementation**

- Remove go_kraken in `go.mod`
- Remove kraken_ws_endpoint from config.json files
- Reuse former functions from v0.0.1 in `ports/socket_utils.go`
- Reimplement `go_kraken` behavior using `gorilla/websocket` package in `ports/kraken_websocket.go`
- add `TestStop` in `kraken_websocket_test.go`

it closes #13 
it closes #20 
it closes #19

please @tiero review this

### CODE REVIEW

File: internal/ports/socket_utils.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
+package ports
```
Comment (tiero) [inline internal/ports/socket_utils.go:1]: I would rename the file just `socket` or `socketutil`
